### PR TITLE
Prototype for Responsive version

### PR DESCRIPTION
**Pull request by dfosco**
Still WIP, but has style improvements that should be rebased in other branches.

Pls review @tamorim @brenoc @amoreira

### CODE REVIEW

**Comment by dfosco** [comment]
@amoreira This PR fixes the issue of images being squished.

**Comment by tamorim** [comment]
image

@dfosco Broken :/

**Comment by dfosco** [comment]
@tamorim Are you sure? Try pulling again, I did a force push a while back

**Comment by dfosco** [comment]
@tamorim @amoreira Adjusments are done on the layout level, but we should sit together to use react-slick here to show the right amount of products based on viewport.

There's currently a JS bug as well that's breaking the shelf after the second product.

**Comment by dfosco** [comment]
We should merge this and open a new PR to close this iteration using react-slick

**Comment by amoreira** [comment]
@dfosco it seems that the images are deforming.

##### Actual
image-errada

#### Expected
image-certa

**Comment by dfosco** [comment]
@amoreira @tamorim All right, I was testing on square images... that was a dumb thing to do.

I'm still not in love with the layout, but it's a solid MVP — although I still need @tamorim to finish the functionality. We should discuss migrating to Bootstrap 4 as soon as possible, to see if we can use `flexbox` for trickier layouts.

As always: pls review.

**Comment by amoreira** [comment]
@dfosco is still broken in the desktop version. =(

desktop-image-error

**Comment by dfosco** [comment]
@amoreira It's not ideal in every viewport because the images have different aspect ratios.

If we don't use flexbox, we will have to choose between:

- Cropping some images at some viewports (current)

- Having a shelf with different heights for different images

- Using JS to dynamically get the image size and adjust the layout accordingly

**Comment by dfosco** [comment]
Another option is to squeeze the images, like we were doing before 😁

It's easy to control the layout when you lock the size of the images, but because we can have product images in different sizes, we have to deal with all of these edge cases 😓

**Comment by tamorim** [comment]
@dfosco I'll leave it to you to fix the slick buttons. Currently they are extending beyond the width viewport, ruining mobile experience D:

**Comment by tamorim** [comment]
@dfosco Can you review it, please?

**Comment by dfosco** [comment]
@tamorim Sure, right away

**Comment by dfosco** [comment]
@tamorim Weird behavior when quickly scrolling through the products
shelf-wtf

**Comment by dfosco** [comment]
To further clarify: when I click on the end of the list, it blinks before serving me the last 4 itens. When I click really fast, it seems to advance through an invisible number of products, taking me ages to “go back” to the actual list

**Comment by dfosco** [comment]
@tamorim Other than this issue, excellent work on making the arrows right for every viewport — wanna know better how you fixed it!

:sparkles:

**Comment by dfosco** [comment]
@tamorim Haven't we merged this yet?

**Comment by tamorim** [comment]
@dfosco Nope, remember that we have that bug that all becomes blank when you click too fast? ):

**Comment by dfosco** [comment]
@tamorim Damn, we needed to merge that so Afonso can go into beta :/

**Comment by tamorim** [comment]
@dfosco Tomorrow we can try to work this out, what do you think?

**Comment by dfosco** [comment]
Sure!

**Pull request merged**
